---
default_roles:
  - system # always top
  - aerospace
  - asdf
  - bitwarden
  - alacritty
  - aldente
  # - asciiquarium
  # - bash
  - bat
  # - btop
  # - discord
  - docker
  # - flatpak
  # - fonts
  - fonts
  - fzf
  # - gh
  # - git
  # - go
  - hammerspoon
  # - helm
  # - k8s
  # - k9s
  - karabiner
  # - kitty
  - lazygit
  - lazydocker
  # - lsd
  # - lua
  # - nala
  # - ncdu
  # - neofetch
  - nvim
  # - nerdfetch
  # - npm
  # - nvm
  # - obsidian
  # - podman
  # - pwsh
  # - python
  - pgcli
  # - raycast
  # # - ruby
  # # - rust
  - ripgrep
  # - slides
  # - spotify
  # - ssh
  # - sshfs
  # - starship
  # - taskfile
  # - terraform
  # - terragrunt
  # - tldr
  # - tmate
  - tmux
  - yazi
  # # - tshark
  # - warp
  # - whalebrew
  # # - zellij
  - zoxide
  - zsh
username: "genzade"
git_user_name: "genzade"
op:
  git:
    user:
      email: "12967144+genzade@users.noreply.github.com"
      # ssh:
      #   github:
      #     techdufus:
      #       - name: id_ed25519
      #         vault_path: "op://Personal/genzade SSH"
      #       - name: raft-infra
      #         vault_path: "op://Raft/Raft-SSH"
asdf_plugins:
  - name: nodejs
    repo: https://github.com/asdf-vm/asdf-nodejs.git
  - name: ruby
    repo: https://github.com/asdf-vm/asdf-ruby.git
  # - name: python
  #   repo: https://github.com/asdf-community/asdf-python.git
  - name: yarn
    repo: https://github.com/twuni/asdf-yarn.git
  - name: golang
    repo: https://github.com/asdf-community/asdf-golang.git
  - name: kubectl
    repo: https://github.com/asdf-community/asdf-kubectl.git
# k8s:
#   repo:
#     version: "v1.26"
# helm:
#   repos:
#     - name: traefik
#       url: https://helm.traefik.io/traefik
# go:
#   packages:
#     - package: github.com/go-task/task/v3/cmd/task@latest
#       cmd: task
#     - package: github.com/gcla/termshark/v2/cmd/termshark@v2.4.0
#       cmd: termshark
#     # - package: github.com/stillmatic/chat@latest
#     #   cmd: chat
