---
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: distribution_config
- name: "{{ role_name }} | Run Tasks: {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: distribution_config.stat.exists
- name: "{{ role_name }} | {{ ansible_facts['distribution'] }} | Link dotfiles config"
  ansible.builtin.command:
    cmd: stow --target={{ ansible_facts['env']['HOME'] }} asdf --ignore=config --verbose=2
    chdir: "{{ ansible_facts['env']['HOME'] }}/dotfiles"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'
  become: false
- name: "{{ role_name }} | {{ ansible_facts['distribution'] }} | Add ASDF Plugins"
  ansible.builtin.command: "asdf plugin add {{ item.name }} {{ item.repo }}"
  loop: "{{ asdf_plugins }}"
- name: "{{ role_name }} | {{ ansible_facts['distribution'] }} | Install Plugins"
  ansible.builtin.command:
    cmd: asdf install
    chdir: "{{ ansible_facts['env']['HOME'] }}"
